import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('weather_category', (table) => {
    table
      .specificType('weather_category_id', 'smallint GENERATED BY DEFAULT AS IDENTITY')
      .primary();
    table.string('name').notNullable().unique();
    table.smallint('sort_order').notNullable();
    table.boolean('is_active').notNullable().defaultTo(true);
  });

  // Wire the FK that dpr had to defer.
  await knex.schema.alterTable('dpr', (table) => {
    table.foreign('weather_category_id').references('weather_category_id').inTable('weather_category');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('dpr', (table) => {
    table.dropForeign('weather_category_id');
  });
  await knex.schema.dropTableIfExists('weather_category');
}
