import type { Knex } from 'knex';

// Grant IDENTITY to programs.program_id in place so API inserts don't need to supply an id.
// The initial programs migration created it as a plain smallint PK.
export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    ALTER TABLE programs ALTER COLUMN program_id ADD GENERATED BY DEFAULT AS IDENTITY;
  `);
  // Seeds set the sequence past the max; this is a safety net for environments that
  // apply the migration without re-running the seed.
  await knex.raw(`
    SELECT setval(
      pg_get_serial_sequence('programs','program_id'),
      COALESCE((SELECT MAX(program_id) FROM programs), 0) + 1,
      false
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`ALTER TABLE programs ALTER COLUMN program_id DROP IDENTITY IF EXISTS;`);
}
