import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('risk_category', (table) => {
    table
      .specificType('risk_category_id', 'smallint GENERATED BY DEFAULT AS IDENTITY')
      .primary();
    table.string('code').notNullable().unique();
    table.string('name').notNullable();
    table.boolean('is_system').notNullable().defaultTo(false);
    table.smallint('sort_order').notNullable();
    table.boolean('is_active').notNullable().defaultTo(true);
  });

  // Wire the FK that risk had to defer.
  await knex.schema.alterTable('risk', (table) => {
    table.foreign('category_id').references('risk_category_id').inTable('risk_category');
  });

  // Required by AC-SCH-21: auto-overdue risks use this category.
  await knex('risk_category')
    .insert({ code: 'schedule_slippage', name: 'Schedule slippage', is_system: true, sort_order: 1 })
    .onConflict('code')
    .ignore();
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('risk', (table) => {
    table.dropForeign('category_id');
  });
  await knex.schema.dropTableIfExists('risk_category');
}
