import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('personnel_role', (table) => {
    table
      .specificType('personnel_role_id', 'smallint GENERATED BY DEFAULT AS IDENTITY')
      .primary();
    table.string('name').notNullable().unique();
    table.smallint('sort_order').notNullable();
    table.boolean('is_active').notNullable().defaultTo(true);
  });

  // Wire the FK that dpr_personnel_role_count had to defer.
  await knex.schema.alterTable('dpr_personnel_role_count', (table) => {
    table.foreign('personnel_role_id').references('personnel_role_id').inTable('personnel_role');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('dpr_personnel_role_count', (table) => {
    table.dropForeign('personnel_role_id');
  });
  await knex.schema.dropTableIfExists('personnel_role');
}
