import type { Knex } from 'knex';

const AUDIT_CHANNELS = [
  'web',
  'mobile',
  'schedule_service',
  'scheduled_job',
  'admin_console',
] as const;

/**
 * Partitioned by occurred_at. Partition management (adding monthly partitions,
 * detaching old ones for cold storage) is an ops concern — a default partition
 * is created here so inserts work from day one.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.raw(
    `CREATE TYPE audit_channel AS ENUM (${AUDIT_CHANNELS.map((c) => `'${c}'`).join(', ')})`,
  );

  await knex.raw(`
    CREATE TABLE audit_event (
      event_id             bigint      GENERATED BY DEFAULT AS IDENTITY,
      occurred_at          timestamptz NOT NULL,
      actor_id             uuid        NOT NULL REFERENCES users (id),
      acting_attribute_id  uuid        REFERENCES roles (attribute_id),
      channel              audit_channel NOT NULL,
      correlation_id       uuid        NOT NULL,
      project_id           uuid        REFERENCES projects (project_id),
      entity_type          text        NOT NULL,
      entity_id            text        NOT NULL,
      action               text        NOT NULL,
      before_json          jsonb,
      after_json           jsonb,
      reason               text,
      ip_address           inet,
      PRIMARY KEY (event_id, occurred_at)
    ) PARTITION BY RANGE (occurred_at)
  `);

  // ponytail: default partition catches everything until ops adds monthly partitions.
  // When monthly partitions exist, detach-and-drain the default before writing more.
  await knex.raw(
    `CREATE TABLE audit_event_default PARTITION OF audit_event DEFAULT`,
  );

  // Indexes on the parent cascade to every partition.
  await knex.schema.alterTable('audit_event', (table) => {
    table.index(['correlation_id'], 'ix_audit_correlation');
    table.index(['project_id', 'occurred_at'], 'ix_audit_project_time');
    table.index(['entity_type', 'entity_id', 'occurred_at'], 'ix_audit_entity_time');
    table.index(['actor_id', 'occurred_at'], 'ix_audit_actor_time');
    table.index(['action', 'occurred_at'], 'ix_audit_action_time');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`DROP TABLE IF EXISTS audit_event CASCADE`);
  await knex.raw(`DROP TYPE IF EXISTS audit_channel`);
}
