import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('holiday_calendar', (table) => {
    table
      .specificType('calendar_id', 'smallint GENERATED BY DEFAULT AS IDENTITY')
      .primary();
    table.string('name').notNullable().unique();
    table.specificType('country_code', 'char(2)').notNullable();
    table.boolean('is_active').notNullable().defaultTo(true);
  });

  // Wire the FK that projects had to defer.
  await knex.schema.alterTable('projects', (table) => {
    table.foreign('holiday_calendar_id').references('calendar_id').inTable('holiday_calendar');
  });

  await knex('holiday_calendar')
    .insert({ name: 'Kenya public holidays', country_code: 'KE' })
    .onConflict('name')
    .ignore();
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('projects', (table) => {
    table.dropForeign('holiday_calendar_id');
  });
  await knex.schema.dropTableIfExists('holiday_calendar');
}
